%"""
%Unit tests for biotracs.openms.AlignmentAssessmentWorkflow
%* License: BIOASTER License
%* Created: 2017
%Omics Hub, Bioinformatics team, BIOASTER Technology Research Institute (http://www.bioaster.org)
%"""

function testAlignmentAssessmentWorkflow( cleanAll )
    if nargin == 0 || cleanAll
        clc; close all force;
        restoredefaultpath();
    end
    addpath('../../../../');
    autoload( ...
        'Dependencies', {...
            '../Prism/matlab', ...
            '../Biocode/matlab', ...
            '../Biocode/matlab/backcomp:r', ...
            '../Bioapps/OpenMS', ...
            '../Bioapps/MzConvert', ...
        }, ...
        'Variables', struct(...
            'OpenMSBinPath', 'C:/Program Files/OpenMS-2.3.0/bin/', ...
            'XtandemExecPath', 'C:\Program Files (x86)\Xtandem\tandem-win-15-12-15-2\bin\tandem.exe', ...
            'MascotServerHostName', '10.69.20.18', ...
            'MascotServerPort', 80, ...
            'MascotServerPath', '/mascot', ...
            'MascotUseProxy', false, ...
            'MascotLogin', false ...
        ) ...
    );

    %% Tests
    import matlab.unittest.TestSuite;
    Tests = TestSuite.fromFile('./model/AlignmentAssessmentWorkflowTests.m');
    Tests.run();
end