%"""
%Unit tests for biotracs.openms.*
%* License: BIOASTER License
%* Created: 2016
%Bioinformatics team, Omics Hub, BIOASTER Technology Research Institute (http://www.bioaster.org)
%"""

function testOpenms( cleanAll )
    if nargin == 0 || cleanAll
        clc; close all force;
        restoredefaultpath();
    end
    
    autoload( ...
        'PkgPaths', {fullfile(pwd, '../../')}, ...
        'Dependencies', {...
            'biotracs-m-openms', ...
        }, ...
        'Variables',  struct(...
            'OpenMSBinPath', 'C:/Program Files/OpenMS-2.3.0/bin/', ...
            'XtandemExecPath', 'C:\Program Files (x86)\Xtandem\tandem-win-15-12-15-2\bin\tandem.exe', ...
            'MascotServerHostName', '10.69.20.18', ...
            'MascotServerPort', 80, ...
            'MascotServerPath', '/mascot', ...
            'MascotUseProxy', false, ...
            'MascotLogin', false ...
        ) ...
    );

    %% Base tests
    import matlab.unittest.TestSuite;
    Tests = TestSuite.fromFolder('./', 'IncludingSubfolders', true);
%     Tests= TestSuite.fromFile('./bioapps/openms/model/MapAlignerPoseClusteringTests.m');
%     Tests = TestSuite.fromFile('./bioapps/openms/model/MetaboWorkflowTests.m');
%     Tests = TestSuite.fromFile('./bioapps/openms/model/ProteoWorkflowTests.m');
%     Tests = TestSuite.fromFile('./bioapps/openms/model/ProteoMascotWorkflowTests.m');
%     Tests = TestSuite.fromFile('./bioapps/openms/model/AlignmentAssessmentWorkflowTests.m');
    Tests.run;
end