% BIOASTER
%> @file		FeatureFinderMetaboConfig.m
%> @class		biotracs.openms.model.FeatureFinderMetaboConfig
%> @link		http://www.bioaster.org
%> @copyright	Copyright (c) 2014, Bioaster Technology Research Institute (http://www.bioaster.org)
%> @license		BIOASTER
%> @date		2016


classdef FeatureFinderMetaboConfig < biotracs.openms.model.BaseProcessConfig
    
    properties(Constant)
    end
    
    properties(SetAccess = protected)
    end
    
    % -------------------------------------------------------
    % Public methods
    % -------------------------------------------------------
    
    methods
        
        % Constructor
        function this = FeatureFinderMetaboConfig( )
            this@biotracs.openms.model.BaseProcessConfig( );
            this.updateParamValue('OutputFileExtension','featureXML');
            this.createParam('NoiseThresholdInt', 1e4,...
                'Constraint', biotracs.core.constraint.IsPositive(),...
                'Description', 'Intensity threshold below which peaks are regarded as noise. (default: 1e4)');
            this.createParam('MassErrorPpm', 5, ...
                'Constraint', biotracs.core.constraint.IsPositive(),...
                'Description', 'Allowed mass deviation in ppm. (default: 5)');
            this.createParam('MinTraceLength', 3, ...
                'Constraint', biotracs.core.constraint.IsPositive(),...
                'Description', 'Minimum expected length of a mass trace in seconds. (default: 3)');
            this.createParam('MaxTraceLength', -1, ...
                'Constraint', biotracs.core.constraint.IsNumeric(),...
                'Description', 'Maximum expected length of a mass trace in seconds. (default: -1)');
            this.createParam('WidthFiltering', 'auto', ...
                'Constraint', biotracs.core.constraint.IsInSet({'auto', 'off', 'fixed'}),...
                'Description', 'Enable filtering of unlikely peaks widths. The fixed setting filters out mass traces outside the minimum and maximum FWHM interval (set parameters accordingly!). The auto setting filters with the 5 and 95% quantiles of the peak with distribution. For Direct injection use off. Values: off, fixed or auto (default: auto)');
            this.createParam('MassTraceSnrFiltering', true, ...
                'Constraint', biotracs.core.constraint.IsBoolean(),...
                'Description', 'Apply post-filtering by signal-to-noise ratio after smoothing. Values: True or False (default: True)');
            this.createParam('ChargeUpperBound', 3, ...
                'Constraint', biotracs.core.constraint.IsPositive( 'Type', 'integer', 'Strict', true ),...
                'Description', 'Highest charge state to consider. (default: 3)');
            this.createParam('SignalToNoise', 3, ...
                'Constraint', biotracs.core.constraint.IsPositive( 'Type', 'double', 'Strict', true ),...
                'Description', 'Minimum signal-to-noise a mass trace should have. (default: 3)');
            this.createParam('QuantificationMethod', 'area', ...
                'Constraint', biotracs.core.constraint.IsText( ),...
                'Description', 'Method of quantification for mass traces. For LC data area is recommended, median for direct injection data. (default: area)');
            this.createParam('ChromatographicFwhm', 5, ...
                'Constraint', biotracs.core.constraint.IsPositive( 'Type', 'double', 'Strict', true ),...
                'Description', 'Expected chromatographic peak width (in seconds). (default: 5)');
            this.createParam('IsobaricMassSplitting', true, ...
                'Constraint', biotracs.core.constraint.IsBoolean(),...
                'Description', 'Enable splitting of isobaric mass traces by chromatographic peak detection. Disable for direct injection. (default: true)');
            this.createParam('EnableRtFiltering', true, ...
                'Constraint', biotracs.core.constraint.IsBoolean(),...
                'Description', 'Require sufficient overlap in RT while assembling mass traces. Disable for direct injection data. (default: true)');
            this.createParam('ReportConvexHulls', true, ...
                'Constraint', biotracs.core.constraint.IsBoolean(),...
                'Description', 'Augment each reported feature with the convex hull of the underlying mass traces (increases featureXML file size considerably). (default: true)');
            
            this.optionSet.addElements(...
                'NoiseThresholdInt',    biotracs.core.shell.model.Option('-algorithm:common:noise_threshold_int "%g"'), ...
                'QuantificationMethod',    biotracs.core.shell.model.Option('-algorithm:mtd:quant_method "%s"'), ...
                'ChromatographicFwhm',    biotracs.core.shell.model.Option('-algorithm:common:chrom_fwhm "%g"'), ...
                'IsobaricMassSplitting',    biotracs.core.shell.model.Option('-algorithm:epd:enabled "%s"', 'FormatFunction', @(x)this.doFormatBoolean(x)), ...
                'EnableRtFiltering',    biotracs.core.shell.model.Option('-algorithm:ffm:enable_RT_filtering "%s"', 'FormatFunction', @(x)this.doFormatBoolean(x)), ...
                'ReportConvexHulls',    biotracs.core.shell.model.Option('-algorithm:ffm:report_convex_hulls "%s"', 'FormatFunction', @(x)this.doFormatBoolean(x)), ...
                'MassErrorPpm',         biotracs.core.shell.model.Option('-algorithm:mtd:mass_error_ppm "%g"'), ...
                'MinTraceLength',       biotracs.core.shell.model.Option('-algorithm:mtd:min_trace_length "%g"'), ...
                'MaxTraceLength',       biotracs.core.shell.model.Option('-algorithm:mtd:max_trace_length "%g"'), ...
                'WidthFiltering',         biotracs.core.shell.model.Option('-algorithm:epd:width_filtering "%s"'), ...
                'MassTraceSnrFiltering',  biotracs.core.shell.model.Option('-algorithm:epd:masstrace_snr_filtering "%s"', 'FormatFunction', @(x)this.doFormatBoolean(x)), ...
                'ChargeUpperBound',       biotracs.core.shell.model.Option('-algorithm:ffm:charge_upper_bound "%d"'), ...
                'SignalToNoise',       biotracs.core.shell.model.Option('-algorithm:common:chrom_peak_snr "%d"') ...
                );
            
        end
        
    end
    
    % -------------------------------------------------------
    % Protected methods
    % -------------------------------------------------------
    
    methods(Access = protected)
        
    end
    
end
